FROM mcr.microsoft.com/devcontainers/typescript-node:24

ENV RUST_VERSION=1.96.0
RUN <<EOF
	set -e
	curl https://static.rust-lang.org/dist/rust-$RUST_VERSION-x86_64-unknown-linux-gnu.tar.xz -o rust.tar.xz
	tar xf rust.tar.xz
	./rust-$RUST_VERSION-x86_64-unknown-linux-gnu/install.sh
EOF

RUN <<EOF
	mkdir /var/space
	chown 1000:1000 /var/space
EOF
